[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
no_faces = false,
'''
position = "before"
payload = '''
remove_random_suit = false,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
card_protos = {}
'''
position = "before"
payload = '''
local remove_suit = nil
if self.GAME.starting_params.remove_random_suit then remove_suit = pseudorandom_element({"H", "D", "C", "S"}, 'cod_triangle') end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if self.GAME.starting_params.no_faces and SMODS.Ranks[v.value].face then keep = false end
'''
position = "before"
payload = '''
if self.GAME.starting_params.remove_random_suit and remove_suit == _s then keep = false end
'''
match_indent = true